package share.commands.dto

enum class CommandType {
    ADD, ADD_IF_MIN, CLEAR, EXECUTE_FILE,
    EXIT, HELP, HISTORY, INFO, PRINT_FIELD_DESCENDING_SCREENWRITER,
    REMOVE, REMOVE_GREATER, SAVE, SHOW, SUM_OF_LENGTH, UPDATE, PRINT_UNIQUE_GENRE,
    DISCONNECT, GET_ALL
}